# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-17 07:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rep_queue',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('describe', models.CharField(max_length=100, verbose_name='\u961f\u5217\u63cf\u8ff0')),
                ('src_ip', models.GenericIPAddressField(verbose_name='\u6e90\u7aefIP')),
                ('src_path', models.CharField(max_length=100, verbose_name='\u6e90\u7aef\u8def\u5f84')),
                ('tgt_ip', models.GenericIPAddressField(verbose_name='\u76ee\u6807\u7aefIP')),
                ('tgt_path', models.CharField(max_length=100, verbose_name='\u76ee\u6807\u7aef\u8def\u5f84')),
                ('add_user', models.CharField(max_length=50, verbose_name='\u6dfb\u52a0\u7528\u6237')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4fe1\u606f\u6dfb\u52a0\u65f6\u95f4')),
            ],
        ),
    ]
