# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-19 05:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rep_queue',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('describe', models.CharField(max_length=100, verbose_name='\u961f\u5217\u63cf\u8ff0')),
                ('src_ip', models.GenericIPAddressField(verbose_name='\u6e90\u7aefIP')),
                ('src_path', models.CharField(max_length=100, verbose_name='\u6e90\u7aef\u8def\u5f84')),
                ('src_ssh_user', models.CharField(max_length=20, verbose_name='\u6e90\u7aefssh\u7528\u6237\u540d')),
                ('src_ssh_pwd', models.CharField(max_length=20, verbose_name='\u6e90\u7aefssh\u5bc6\u7801')),
                ('tgt_ip', models.GenericIPAddressField(verbose_name='\u76ee\u6807\u7aefIP')),
                ('tgt_path', models.CharField(max_length=100, verbose_name='\u76ee\u6807\u7aef\u8def\u5f84')),
                ('tgt_ssh_user', models.CharField(max_length=20, verbose_name='\u76ee\u6807\u7aefssh\u7528\u6237\u540d')),
                ('tgt_ssh_pwd', models.CharField(max_length=20, verbose_name='\u76ee\u6807\u7aefssh\u5bc6\u7801')),
                ('add_user', models.CharField(default='---------', max_length=50, verbose_name='\u6dfb\u52a0\u7528\u6237')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4fe1\u606f\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'rep_queue',
                'verbose_name': '\u961f\u5217\u914d\u7f6e\u8868',
                'verbose_name_plural': '\u961f\u5217\u914d\u7f6e\u8868',
            },
        ),
        migrations.CreateModel(
            name='sys_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs', models.CharField(max_length=1000, verbose_name='\u8fd0\u7ef4\u7cfb\u7edf\u65e5\u5fd7\u4fe1\u606f')),
                ('errs', models.CharField(max_length=1000, verbose_name='\u8fd0\u7ef4\u7cfb\u7edf\u65e5\u5fd7\u62a5\u9519\u4fe1\u606f')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u65e5\u5fd7\u6dfb\u52a0\u65f6\u95f4')),
            ],
        ),
    ]
