# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-24 05:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rep_queue',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('describe', models.CharField(max_length=100, verbose_name='\u961f\u5217\u63cf\u8ff0')),
                ('src_ip', models.GenericIPAddressField(verbose_name='\u6e90\u7aefIP')),
                ('src_path', models.CharField(max_length=100, verbose_name='\u6e90\u7aef\u8def\u5f84')),
                ('src_ssh_user', models.CharField(max_length=20, verbose_name='\u6e90\u7aefssh\u7528\u6237\u540d')),
                ('src_ssh_pwd', models.CharField(max_length=20, verbose_name='\u6e90\u7aefssh\u5bc6\u7801')),
                ('tgt_ip', models.GenericIPAddressField(verbose_name='\u76ee\u6807\u7aefIP')),
                ('tgt_path', models.CharField(max_length=100, verbose_name='\u76ee\u6807\u7aef\u8def\u5f84')),
                ('tgt_ssh_user', models.CharField(max_length=20, verbose_name='\u76ee\u6807\u7aefssh\u7528\u6237\u540d')),
                ('tgt_ssh_pwd', models.CharField(max_length=20, verbose_name='\u76ee\u6807\u7aefssh\u5bc6\u7801')),
                ('add_user', models.CharField(default='---------', max_length=50, verbose_name='\u6dfb\u52a0\u7528\u6237')),
                ('script_path', models.CharField(max_length=50, verbose_name='\u8fdc\u7a0b\u811a\u672c\u76ee\u5f55')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4fe1\u606f\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'rep_queue',
                'verbose_name': '\u961f\u5217\u914d\u7f6e\u8868',
                'verbose_name_plural': '\u961f\u5217\u914d\u7f6e\u8868',
            },
        ),
        migrations.CreateModel(
            name='src_moni_info',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('src_ssh_status', models.IntegerField(default=0, verbose_name='\u6e90\u7aefssh\u8fde\u901a\u72b6\u6001')),
                ('src_path_status', models.IntegerField(default=0, verbose_name='\u6e90\u7aef\u7aef\u76ee\u5f55\u72b6\u6001')),
                ('dbps_cnt', models.IntegerField(verbose_name='dbps\u8fdb\u7a0b\u6570')),
                ('capture_cnt', models.IntegerField(verbose_name='\u5206\u6790\u8fdb\u7a0b\u6570')),
                ('sender_cnt', models.IntegerField(verbose_name='\u4f20\u8f93\u8fdb\u7a0b\u6570')),
                ('capture_rate', models.CharField(max_length=20, verbose_name='\u5206\u6790\u5230\u7684\u5e8f\u5217\u53f7')),
                ('capture_err', models.CharField(max_length=100, verbose_name='\u5206\u6790\u62a5\u9519\u4fe1\u606f')),
                ('sender_err', models.CharField(max_length=100, null=True, verbose_name='\u4f20\u8f93\u8fdb\u7a0b\u62a5\u9519\u4fe1\u606f')),
                ('active', models.IntegerField(default=0, verbose_name='\u961f\u5217\u52a8\u4f5c')),
                ('queue_id', models.IntegerField(verbose_name='\u961f\u5217ID\u4fe1\u606f')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u76d1\u63a7\u4fe1\u606f\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'src_moni_info',
                'verbose_name': '\u6e90\u7aef\u76d1\u63a7\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u6e90\u7aef\u76d1\u63a7\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='sys_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs', models.CharField(max_length=1000, verbose_name='\u8fd0\u7ef4\u7cfb\u7edf\u65e5\u5fd7\u4fe1\u606f')),
                ('errs', models.CharField(max_length=1000, verbose_name='\u8fd0\u7ef4\u7cfb\u7edf\u65e5\u5fd7\u62a5\u9519\u4fe1\u606f')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u65e5\u5fd7\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'sys_logs',
                'verbose_name': '\u7cfb\u7edf\u65e5\u5fd7\u8868',
                'verbose_name_plural': '\u7cfb\u7edf\u65e5\u5fd7\u8868',
            },
        ),
        migrations.CreateModel(
            name='tgt_moni_info',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tgt_ssh_status', models.IntegerField(default=0, verbose_name='\u76ee\u6807\u7aefssh\u8fde\u901a\u72b6\u6001')),
                ('tgt_path_status', models.IntegerField(default=0, verbose_name='\u76ee\u6807\u7aef\u76ee\u5f55\u72b6\u6001')),
                ('collect_cnt', models.IntegerField(verbose_name='\u63a5\u6536\u8fdb\u7a0b\u6570')),
                ('collect_err', models.CharField(max_length=100, null=True, verbose_name='\u63a5\u6536\u8fdb\u7a0b\u62a5\u9519\u4fe1\u606f')),
                ('loader_s_cnt', models.IntegerField(default=0, verbose_name='\u5168\u91cf\u52a0\u8f7d\u8fdb\u7a0b\u6570')),
                ('loader_r_cnt', models.IntegerField(default=0, verbose_name='\u589e\u91cf\u52a0\u8f7d\u8fdb\u7a0b\u6570')),
                ('loader_message', models.CharField(max_length=100, null=True, verbose_name='\u52a0\u8f7d\u4fe1\u606f')),
                ('loader_time', models.CharField(max_length=100, null=True, verbose_name='\u52a0\u8f7d\u65f6\u95f4\u4fe1\u606f')),
                ('loader_err', models.CharField(max_length=100, null=True, verbose_name='\u52a0\u8f7d\u62a5\u9519\u4fe1\u606f')),
                ('active', models.IntegerField(default=0, verbose_name='\u961f\u5217\u52a8\u4f5c')),
                ('queue_id', models.IntegerField(verbose_name='\u961f\u5217ID\u4fe1\u606f')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u76d1\u63a7\u4fe1\u606f\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'tgt_moni_info',
                'verbose_name': '\u76ee\u6807\u7aef\u76d1\u63a7\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u76ee\u6807\u7aef\u76d1\u63a7\u4fe1\u606f\u8868',
            },
        ),
    ]
