# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-12 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='p_mes',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('paddr', models.CharField(max_length=15)),
                ('ptel', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='p_mes',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.person'),
        ),
    ]
