# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-17 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rep_queue',
            options={'verbose_name': '\u961f\u5217\u914d\u7f6e\u8868', 'verbose_name_plural': '\u961f\u5217\u914d\u7f6e\u8868'},
        ),
        migrations.AlterModelTable(
            name='rep_queue',
            table='rep_queue',
        ),
    ]
