# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-19 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sys_logs',
            options={'verbose_name': '\u7cfb\u7edf\u65e5\u5fd7\u8868', 'verbose_name_plural': '\u7cfb\u7edf\u65e5\u5fd7\u8868'},
        ),
        migrations.AlterModelTable(
            name='sys_logs',
            table='sys_logs',
        ),
    ]
