# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-25 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='src_moni_info',
            name='script_path_status',
            field=models.IntegerField(default=0, verbose_name='\u8fdc\u7a0b\u811a\u672c\u76ee\u5f55\u72b6\u6001'),
        ),
    ]
