# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-17 08:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_auto_20170417_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep_queue',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
