# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-25 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_src_moni_info_script_path_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='src_moni_info',
            name='capture_cnt',
            field=models.IntegerField(null=True, verbose_name='\u5206\u6790\u8fdb\u7a0b\u6570'),
        ),
        migrations.AlterField(
            model_name='src_moni_info',
            name='capture_err',
            field=models.CharField(max_length=100, null=True, verbose_name='\u5206\u6790\u62a5\u9519\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='src_moni_info',
            name='dbps_cnt',
            field=models.IntegerField(null=True, verbose_name='dbps\u8fdb\u7a0b\u6570'),
        ),
        migrations.AlterField(
            model_name='src_moni_info',
            name='sender_cnt',
            field=models.IntegerField(null=True, verbose_name='\u4f20\u8f93\u8fdb\u7a0b\u6570'),
        ),
    ]
