# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-25 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_auto_20170425_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='src_moni_info',
            name='capture_rate',
            field=models.CharField(max_length=20, null=True, verbose_name='\u5206\u6790\u5230\u7684\u5e8f\u5217\u53f7'),
        ),
        migrations.AlterField(
            model_name='src_moni_info',
            name='queue_id',
            field=models.IntegerField(null=True, verbose_name='\u961f\u5217ID\u4fe1\u606f'),
        ),
    ]
