# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-25 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_auto_20170512_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='src_moni_info',
            name='capture_rate',
            field=models.CharField(max_length=20, null=True, verbose_name='\u5206\u6790\u5230\u7684\u5e8f\u5217\u53f7'),
        ),
        migrations.AddField(
            model_name='src_moni_info',
            name='sync_status',
            field=models.IntegerField(null=True, verbose_name='\u540c\u6b65\u72b6\u6001'),
        ),
    ]
