# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-25 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_auto_20170425_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='src_moni_info',
            name='active',
            field=models.IntegerField(null=True, verbose_name='\u961f\u5217\u52a8\u4f5c'),
        ),
    ]
