# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-25 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0005_auto_20170425_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='src_moni_info',
            name='add_time',
            field=models.DateTimeField(null=True, verbose_name='\u76d1\u63a7\u4fe1\u606f\u6dfb\u52a0\u65f6\u95f4'),
        ),
    ]
