# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-26 01:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0006_auto_20170425_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='src_moni_info',
            name='capture_rate',
        ),
        migrations.AlterField(
            model_name='src_moni_info',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u76d1\u63a7\u4fe1\u606f\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='src_moni_info',
            name='queue_id',
            field=models.IntegerField(verbose_name='\u961f\u5217ID\u4fe1\u606f'),
        ),
    ]
