# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-02 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0007_auto_20170426_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgt_moni_info',
            name='loader_message',
        ),
        migrations.AddField(
            model_name='tgt_moni_info',
            name='loader_rate',
            field=models.CharField(max_length=200, null=True, verbose_name='\u52a0\u8f7d\u8fdb\u5ea6\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='tgt_moni_info',
            name='sync_status',
            field=models.IntegerField(default=0, verbose_name='\u540c\u6b65\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='tgt_moni_info',
            name='active',
            field=models.IntegerField(default=0, verbose_name='\u540c\u6b65\u52a8\u4f5c'),
        ),
        migrations.AlterField(
            model_name='tgt_moni_info',
            name='collect_cnt',
            field=models.IntegerField(null=True, verbose_name='\u63a5\u6536\u8fdb\u7a0b\u6570'),
        ),
        migrations.AlterField(
            model_name='tgt_moni_info',
            name='collect_err',
            field=models.CharField(max_length=200, null=True, verbose_name='\u63a5\u6536\u8fdb\u7a0b\u62a5\u9519\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='tgt_moni_info',
            name='loader_err',
            field=models.CharField(max_length=200, null=True, verbose_name='\u52a0\u8f7d\u62a5\u9519\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='tgt_moni_info',
            name='loader_r_cnt',
            field=models.IntegerField(null=True, verbose_name='\u589e\u91cf\u52a0\u8f7d\u8fdb\u7a0b\u6570'),
        ),
        migrations.AlterField(
            model_name='tgt_moni_info',
            name='loader_s_cnt',
            field=models.IntegerField(null=True, verbose_name='\u5168\u91cf\u52a0\u8f7d\u8fdb\u7a0b\u6570'),
        ),
        migrations.AlterField(
            model_name='tgt_moni_info',
            name='loader_time',
            field=models.CharField(max_length=200, null=True, verbose_name='\u52a0\u8f7d\u65f6\u95f4\u4fe1\u606f'),
        ),
    ]
