# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-02 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0008_auto_20170502_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rep_queue',
            old_name='script_path',
            new_name='src_script_path',
        ),
        migrations.AddField(
            model_name='rep_queue',
            name='tgt_script_path',
            field=models.CharField(max_length=50, null=True, verbose_name='\u8fdc\u7a0b\u811a\u672c\u76ee\u5f55'),
        ),
        migrations.AddField(
            model_name='tgt_moni_info',
            name='script_path_status',
            field=models.IntegerField(default=0, verbose_name='\u76ee\u6807\u7aef\u8fdc\u7a0b\u811a\u672c\u76ee\u5f55\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='src_moni_info',
            name='script_path_status',
            field=models.IntegerField(default=0, verbose_name='\u6e90\u7aef\u8fdc\u7a0b\u811a\u672c\u76ee\u5f55\u72b6\u6001'),
        ),
    ]
