# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-03 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0009_auto_20170502_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgt_moni_info',
            name='loader_r_p_cnt',
            field=models.IntegerField(null=True, verbose_name='\u589e\u91cf\u52a0\u8f7d\u914d\u7f6e\u8fdb\u7a0b\u6570'),
        ),
        migrations.AddField(
            model_name='tgt_moni_info',
            name='loader_s_p_cnt',
            field=models.IntegerField(null=True, verbose_name='\u5168\u91cf\u52a0\u8f7d\u914d\u7f6e\u8fdb\u7a0b\u6570'),
        ),
    ]
